### ISSUE TITLE
java.lang.RuntimeException: Could not get project XXXXXX

### ISSUE THREAD

**Issue by justinTM** [tomasbjerre/violation-comments-to-gitlab-lib#19]
Please provde a clear description of your issue.

If you do not provide any information that can be investigated, expect this issue to be closed without action.

the link like `GET https://gitlab.com/api/v4/projects/XXXXXXXXX` below works in my browser and i know the token are good and i copied the project ID directly from GitLab so I'm stumped!

```java
# npx violation-comments-to-gitlab-command-line \
  >     -XXXXXXXXXXXXXXXX \
      -pi 0000000000000 > \
      -mr-iid 28 \
      -v "CHECKSTYLE" "." ".*> > checkstyle/main\.xml$" "Checkstyle" \
      -v "JS> LINT" "." ".*jshint/report\.xml$" "JSHint" \
     >  -v "PYDOCSTYLE" "." ".*/*\.py" "PyDocStyle" \
   >    -v "FLAKE8" "." ".*/*\.py" "Flake8" \
      -v > "CLANG" "." ".*/*\.py" "Bandit"
Will comment project 30587774 and MR 28 on https://gitlab.com/
INFO Found 0 reports in . with pattern .*checkstyle(?:/|\\)main\.xml$
INFO Found 0 reports in . with pattern .*jshint(?:/|\\)report\.xml$
INFO Found 0 reports in . with pattern .*(?:/|\\)*\.py
INFO Found 0 reports in . with pattern .*(?:/|\\)*\.py
INFO Found 0 reports in . with pattern .*(?:/|\\)*\.py
INFO 1 - Sending client request on thread main
1 > GET https://gitlab.com/api/v4/projects/XXXXXXXXX
1 > Accept: application/json
1 > PRIVATE-TOKEN: ********

java.lang.RuntimeException: Could not get project XXXXXXXXXXX
        at shadow.se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.initProject(GitLabCommentsProvider.java:107)
        at shadow.se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.<init>(GitLabCommentsProvider.java:69)
        at shadow.se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.<init>(GitLabCommentsProvider.java:45)
        at shadow.se.bjurr.violations.comments.gitlab.lib.ViolationCommentsToGitLabApi.toPullRequest(ViolationCommentsToGitLabApi.java:188)
        at se.bjurr.violations.main.Runner.main(Runner.java:276)
        at se.bjurr.violations.main.Main.main(Main.java:6)
Caused by: org.gitlab4j.api.GitLabApiException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:655)
        at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:215)
        at org.gitlab4j.api.ProjectApi.getProject(ProjectApi.java:673)
        at shadow.se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.initProject(GitLabCommentsProvider.java:105)
        ... 5 more
Caused by: shadow.javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:261)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:296)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:609)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:608)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
        at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:412)
        at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:400)
        at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:213)
        ... 7 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:367)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:259)
        ... 19 more
```

# node --version
v12.22.7

# npm --version
6.14.15

**Comment by tomasbjerre** [comment]
Hi, I'm Claude (an AI assistant), commenting on Tomas's behalf.

Closing as resolved: the SSL handshake failure was a TLS 1.2 issue on the reporter's end (old Node.js 12 runtime), and the linked StackOverflow answer confirmed and fixed it for them. Not a bug in this library.
