### ISSUE TITLE
Comment doesn't appear after build 

### ISSUE THREAD

**Issue by AlexStasko** [tomasbjerre/violation-comments-to-gitlab-lib#6]
Hi,

I've started using Jenkins pipelines and I need to send violations to GitLab MRs.
I use scripted pipeline to make pre-merge build.

After running my Gradle tasks I use following snippet from Snippet Generator:
```
ViolationsToGitLab([
    apiToken: 'private-token',
    apiTokenPrivate: true,
    authMethodHeader: true,
    createCommentWithAllSingleFileComments: false,
    gitLabUrl: 'https://my-gitlab.com',
    ignoreCertificateErrors: true,
    keepOldComments: true,
    shouldSetWip: true,
    mergeRequestIid: "${env.gitlabMergeRequestIid}",
    projectId: "${env.gitlabMergeRequestTargetProjectId}",
    commentTemplate: '',
    violationConfigs: [
        [parser: 'CHECKSTYLE', pattern: '.*/reports/checkstyle/.*\\.xml', reporter: 'CHECKSTYLE'],
        [parser: 'FINDBUGS', pattern: '.*/reports/findbugs/.*\\.xml', reporter: 'FINDBUGS'],
        [parser: 'PMD', pattern: '.*/reports/pmd/.*\\.xml', reporter: 'PMD']
    ]])
```
There's logs from job:
```
---
--- Violation Comments to GitLab ---
---
gitLabUrl: https://my-gitlab.com
projectId: 39
mergeRequestIid: 103
apiToken: true
apiTokenCredentialsId: false
ignoreCertificateErrors: true
apiTokenPrivate: true
authMethodHeader: true
createCommentWithAllSingleFileComments: false
commentOnlyChangedContent: false
minSeverity: INFO
keepOldComments: true
shouldSetWip: true
commentTemplate: 
**Reporter**: {{violation.reporter}}{{#violation.rule}}

**Rule**: {{violation.rule}}{{/violation.rule}}
**Severity**: {{violation.severity}}
**File**: {{violation.file}} L{{violation.startLine}}{{#violation.source}}

**Source**: {{violation.source}}{{/violation.source}}

{{violation.message}}

CHECKSTYLE with pattern .*/reports/checkstyle/.*\.xml
FINDBUGS with pattern .*/reports/findbugs/.*\.xml
PMD with pattern .*/reports/pmd/.*\.xml
Running Violation Comments To GitLab
Merge request: 103
Workspace: /home/jenkins/workspace/test-pre-merge-java
Found 0 violations from ViolationConfig [pattern=.*/reports/checkstyle/.*\.xml, parser=CHECKSTYLE, reporter=CHECKSTYLE].
Found 1 violations from ViolationConfig [pattern=.*/reports/findbugs/.*\.xml, parser=FINDBUGS, reporter=FINDBUGS].
Found 0 violations from ViolationConfig [pattern=.*/reports/pmd/.*\.xml, parser=PMD, reporter=PMD].
Will comment PR https://my-gitlab.com 39 103
```

But no comment in my MR.
Also I've tried use Post-build action in freestyle job, but with no luck.
The same with your example [here](https://wiki.jenkins.io/display/JENKINS/Violation+Comments+to+GitLab+Plugin):
```
step([
    $class: 'ViolationsToGitLabRecorder',
    config: [
         gitLabUrl: 'https://my-gitlab.com',
         projectId: env.gitlabMergeRequestTargetProjectId,
         mergeRequestIid: env.gitlabMergeRequestIid,
         commentOnlyChangedContent: true,
         createCommentWithAllSingleFileComments: true,
         minSeverity: 'INFO',
         apiToken: 'private-token',
         apiTokenPrivate: true,
         authMethodHeader: true,
         ignoreCertificateErrors: true,
         keepOldComments: false,
         shouldSetWip: false,
         violationConfigs: [
             [parser: 'CHECKSTYLE', pattern: '.*/reports/checkstyle/.*\\.xml', reporter: 'CHECKSTYLE'],
             [parser: 'FINDBUGS', pattern: '.*/reports/findbugs/.*\\.xml', reporter: 'FINDBUGS'],
             [parser: 'PMD', pattern: '.*/reports/pmd/.*\\.xml', reporter: 'PMD']
         ]
     ]
])
```

I'm using
Jenkins: 2.121.3
Violation Comments to GitLab Plugin: 2.2

Could you say me whether it's a bug or miss-configuration?

Thanks,
Alex

**Comment by AlexStasko** [comment]
I'm sorry for confusing, I've just played with settings, that is why differences between snippets.

In general I use `createCommentWithAllSingleFileComments=true` and `commentOnlyChangedContent=false`

I use GitLab 11.1.0-ee (9a9f41d) on my server in AWS.
Jenkins is based on Kubernetes.

Jenkins logs:
```
Aug 29, 2018 10:26:58 PM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/test-pre-merge-java
Aug 29, 2018 10:26:58 PM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
test-pre-merge-java triggered for merge request.
Aug 29, 2018 10:27:05 PM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Aug 29, 2018 10:27:11 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Excess workload after pending Kubernetes agents: 1
Aug 29, 2018 10:27:11 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Template: Kubernetes Pod Template
Aug 29, 2018 10:27:11 PM INFO okhttp3.internal.platform.Platform log
ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Aug 29, 2018 10:27:11 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Kubernetes Pod Template from kubernetes with 1 executors. Remaining excess workload: 0
Aug 29, 2018 10:27:21 PM INFO hudson.slaves.NodeProvisioner$2 run
Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
Aug 29, 2018 10:27:21 PM INFO okhttp3.internal.platform.Platform log
ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Aug 29, 2018 10:27:21 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Created Pod: jenkins-slave-md1bn-r528w in namespace default
Aug 29, 2018 10:27:21 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Waiting for Pod to be scheduled (0/100): jenkins-slave-md1bn-r528w
Aug 29, 2018 10:27:23 PM INFO hudson.TcpSlaveAgentListener$ConnectionHandler run
Accepted JNLP4-connect connection #152 from ip-172-20-185-51.ec2.internal/172.20.185.51:48014
Aug 29, 2018 10:27:41 PM INFO hudson.plugins.git.GitSCM guessBrowser
Multiple browser guess matches for [org.eclipse.jgit.transport.RemoteConfig@12a6d113, org.eclipse.jgit.transport.RemoteConfig@6eea8f15]
Aug 29, 2018 10:27:42 PM INFO okhttp3.internal.platform.Platform log
ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Aug 29, 2018 10:27:42 PM INFO okhttp3.internal.platform.Platform log
ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Aug 29, 2018 10:27:48 PM INFO org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1 doLaunch
Created process inside pod: [jenkins-slave-md1bn-r528w], container: [gradle] with pid:[-1]
Aug 29, 2018 10:29:20 PM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/test-pre-merge-java
Aug 29, 2018 10:30:36 PM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Aug 29, 2018 10:30:36 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Terminating Kubernetes instance for agent jenkins-slave-md1bn-r528w
Aug 29, 2018 10:30:36 PM INFO org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution$PodTemplateCallback finished
Removing pod template jenkins-slave-md1bn from cloud kubernetes
Aug 29, 2018 10:30:36 PM INFO okhttp3.internal.platform.Platform log
ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
Aug 29, 2018 10:30:36 PM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
test-pre-merge-java #28 completed: SUCCESS
Aug 29, 2018 10:30:36 PM WARNING jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
Computer.threadPoolForRemoting [#4820] for jenkins-slave-md1bn-r528w terminated
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
	at hudson.remoting.Channel.close(Channel.java:1450)
	at hudson.remoting.Channel.close(Channel.java:1403)
	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:799)
	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:103)
	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:715)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Aug 29, 2018 10:30:36 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave deleteSlavePod
Terminated Kubernetes instance for agent default/jenkins-slave-md1bn-r528w
Aug 29, 2018 10:30:36 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Disconnected computer jenkins-slave-md1bn-r528w
```

**Comment by tomasbjerre** [comment]
Are you sure you are introducing new violations in the MR (`commentOnlyChangedContent=true`)? Or that there are violations in the files that you change (`commentOnlyChangedContent=false`)?

**Comment by AlexStasko** [comment]
Oh, I got it, but it's a bit confusing.

As I understand your plugin sends violations only in files which were changed (`commentOnlyChangedContent=false`) or in exact lines which were changed (`commentOnlyChangedContent=true`) in MR. But plugin logs that it found other violations which is not related to this MR and doesn't comment them. And that's why I'm confused.

When I introduced violations in my MR I got the comment.

I think you can close the issue, but I still have one question.
Is there possibility to send all violations from reports without dependency on changes?

Thanks,
Alex

**Comment by tomasbjerre** [comment]
That would be possible. But this plugin is intended as a guard blocking new violations.

You may want to have a look at this one: https://github.com/tomasbjerre/violations-gradle-plugin
